language: node_js
sudo: false

node_js:
  - "0.12"
  - "iojs"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "node"

matrix:
  allow_failures:
    - node_js: "node"

after_script:
  make coveralls
